AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/seeds.rb'
    - 'config/**/*'
    - 'spec/**/*'
    - 'bin/*'