# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/gifts', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Gift. As you add validations to Gift, be sure to
  # adjust the attributes here as well.
  let(:friend) { Friend.create(name: 'Chuck Testa', birthday: '2022-01-01') }

  let(:valid_attributes) do
    { name: 'Test Gift', friend_id: friend.id }
  end

  let(:invalid_attributes) do
    { attribute1: 'invalid_value1', attribute2: 'invalid_value2' }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Gift.create! valid_attributes
      get gifts_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      gift = Gift.create! valid_attributes
      get gift_url(gift)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_gift_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      gift = Gift.create! valid_attributes
      get edit_gift_url(gift)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Gift' do
        expect do
          post gifts_url, params: { gift: valid_attributes }
        end.to change(Gift, :count).by(1)
      end

      it 'redirects to the created gift' do
        post gifts_url, params: { gift: valid_attributes }
        expect(response).to redirect_to(gift_url(Gift.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Gift' do
        expect do
          post gifts_url, params: { gift: invalid_attributes }
        end.to change(Gift, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post gifts_url, params: { gift: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested gift' do
        gift = Gift.create! valid_attributes
        patch gift_url(gift), params: { gift: new_attributes }
        gift.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the gift' do
        gift = Gift.create! valid_attributes
        patch gift_url(gift), params: { gift: new_attributes }
        gift.reload
        expect(response).to redirect_to(gift_url(gift))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        gift = Gift.create! valid_attributes
        patch gift_url(gift), params: { gift: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested gift' do
      gift = Gift.create! valid_attributes
      expect do
        delete gift_url(gift)
      end.to change(Gift, :count).by(-1)
    end

    it 'redirects to the gifts list' do
      gift = Gift.create! valid_attributes
      delete gift_url(gift)
      expect(response).to redirect_to(gifts_url)
    end
  end
end
